title: Neil Bizzell # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Amazingly talented individual with skills in... 
  <br><br>
  I am looking for work in.... 
  <br><br>
  <a href="https://www.linkedin.com/in/neilbizzell/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
